STAR_RADIUS = 462
STAR_LIMB_DARKENING_COEFFICIENT = 0.80
STAR_LIMB_DARKENING_ALPHA = 0.85

PLANET_RADIUS = 50
PLANET_INCLINATION = -250

MARGIN = 50
NUMBER_OF_WORKERS = 16

_GRID_SIZE = int(2 * (STAR_RADIUS + MARGIN))
_PLANET_Y = int(STAR_RADIUS + MARGIN + PLANET_INCLINATION)
